excluded:
  - ios/Motion
  - ios/Transition
  - ios/ImageViewer.swift

disabled_rules:
  - identifier_name
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  - trailing_comma
  - todo
